spring:
  application:
    name: study-service-one
  zipkin:
    base-url: http://localhost:8003/
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
feign:
  hystrix:
    enabled: true
